### PR TITLE
Added link to Zwave protocol modules

### PR DESCRIPTION
**Pull request by MaxKhlupnov**
Hi there! Microsoft Technology Center Moscow propose two modules for supporting ZWave protocol stack.
Probably we have to relocate to some other repository....
There are to modules - protocol gateway module and mapper for IoT Hub
https://github.com/MaxKhlupnov/SmartHive

### CODE REVIEW

**Comment by aribeironovaes** [comment]
Hi @MaxKhlupnov , 

Thanks a lot for your contribution. 
I would suggest for you to take a look into our Contribution Guideline for a list of things that we require in order to have the module listed: 
Provide documentation for your module, including:

-Licensing terms (OK)
-How to contact someone about the module (Assumint it's ok, since there is the contribution list, if different you should add to the read.me file)
-How to file a bug (Same, assuming you will handle github issues as bugs)
-A description of the module's features (Missing)
-How to install it (Missing)
-How to use it (Missing)

Please, add the let us know. 

Thanks, 

Angelo Ribeiro.

**Comment by MaxKhlupnov** [comment]
Hi @aribeironovaes ! 
Description of the module's features and architecture diagram added.
Work still in progress. Hope we can meet Code standards soon. 
Regards, Max.

**Comment by darobs** [comment]
Hello @MaxKhlupnov,

Any progress on this?  I think the key thing we're missing is how to install and use this module, which I didn't see from a skim of the project documentation.

**Comment by MaxKhlupnov** [comment]
Hello, @aribeironovaes  and @darobs! 
Project documentation updated. 
How to build, install and use instruction was added at https://github.com/MaxKhlupnov/SmartHive .
Sorry for delay.

**Pull request merged**
