### PR TITLE
Iothub remove mandatory source

### PR DESCRIPTION
**Pull request by villepalo**
Removed mandatory source = mapping property. See #394

### CODE REVIEW

**Comment by kiranpradeep** [comment]
The pull request doesn't touch identity mapper module. It only changes iothub module. For completion, shouldn't it change identity mapper too?

**Comment by villepalo** [comment]
It could be that some module uses identityMapper source property for other purposes, it is not necessary for iothub module. So I think idenitymapper module should not be modified in this pull-request.

**Comment by damonbarry** [comment]
For better or worse, source is not part of the message contract for the iothub module. Wouldn't it be a breaking change to remove it? If so, we probably shouldn't take this change.

**Comment by darobs** [comment]
Thank you so much for your contribution. Unfortunately, I'm agreeing with @damonbarry on this.  We're not going to merge this as is out of concern for breaking existing applications, but I think the problem as described does have merit. I did add to our backlog a suggestion:

> Add an optional configuration (something like "AcceptModule": "<module name>" ) that allows IoTHub to accept a message from source=="<module name>"  default will be to accept source==mapping so that changes will not break existing applications.

**Pull request closed without merging**
